[package]
name = "rmercury"
version = "0.0.1"
authors = ["Eric Olson <eric.rob.olson@gmail.com>"]
edition = "2018"

[dev-dependencies.sdl2]
version = "0.33.0"
features = ["bundled"]

[[example]]
name = "basic"